from flask import Flask, render_template, request, jsonify
import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load the hidden environment variables from your .env file
load_dotenv()

app = Flask(__name__)

# --- Gemini API Setup ---
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise ValueError("No API Key found. Please check your .env file.")

genai.configure(api_key=GEMINI_API_KEY)

# Initialize the model
model = genai.GenerativeModel('models/gemini-2.5-flash')

# --- Routes ---
@app.route('/')
def home():
    """Serves the main HTML interface."""
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    """Handles incoming chat messages and returns a response."""
    user_message = request.json.get('message', '')
    
    # Call the Gemini logic
    bot_response = generate_response(user_message)
    
    return jsonify({"response": bot_response})

# --- Gemini Chatbot Logic ---
def generate_response(message):
    try:
        # Send the user's message to the Gemini API
        response = model.generate_content(message)
        
        # Return the text generated by the model
        return response.text
        
    except Exception as e:
        print(f"Error calling Gemini API: {e}")
        return "I'm having trouble connecting to my brain right now. Please check the server logs."

if __name__ == '__main__':
    app.run(debug=True, port=5000)
